# Docker compose file for testing. Use it with:
# docker-compose up --force-recreate

version: "3.5"
services:
  zero1:
    image: dgraph/dgraph:latest
    container_name: bank-dg0.1
    working_dir: /data/dg0.1
    ports:
      - 5080:5080
      - 6080:6080
    command: dgraph zero --my=zero1:5080 --replicas 3 --idx 1 --bindall --expose_trace --profile_mode block --block_rate 10 --logtostderr -v=2

  dg1:
    image: dgraph/dgraph:latest
    container_name: bank-dg1
    working_dir: /data/dg1
    ports:
      - 8180:8180
      - 9180:9180
      - 9999:9999
    security_opt:
      - seccomp:unconfined
    command: dgraph alpha --my=dg1:7180 --lru_mb=1024 --zero=zero1:5080 --expose_trace -o 100 --trace 1.0 --profile_mode block --block_rate 10 --logtostderr -v=3

  node-exporter:
    image: quay.io/prometheus/node-exporter
    container_name: node-exporter
    pid: "host"
    volumes:
      - type: bind
        source: /
        target: /host
        read_only: true

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    ports:
      - "9090:9090"
    volumes:
      - type: bind
        source: $PWD/prometheus.yml
        target: /etc/prometheus/prometheus.yml
        read_only: true

  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    ports:
     - "3000:3000"  

    

